package com.example.climberapp.models

data class PojoDeviceDetail (val deviceDetails: DeviceDetails,
                             val bothclampopen: Long,
                             val childConnection: Long,
                             val sos: Long,
                             val bothclampclosed: Long,
                             val nodata: Long,
                             val free: Long,
                             val currentPage: Long,
                             val clampDetails: List<ClampDetail>,
                             val status: Long)
data class DeviceDetails(
    val id: Long,
    val deviceId: Long,
    val fleetId: Long,
    val createdBy: String,
    val updatedBy: String,
    val createdAt: String,
    val updatedAt: String,
    val issuedTo: String,
    val lastLat: Double,
    val lastLon: Double,
    val live: Long,
    val lastOnsite: Boolean,
    val siteId: String,
    val city: String,
    val lastBattery: Double,
    val sos: Long,
    val isCameraEnabled: Any? = null,
    val lastTouchTime: String,
    val lastTouchDate: String,
    val lastTouchDateTime: String,
    val mobile: String,
    val gsm: Long,
    val lastMsl: Double,
    val lastPosition: Long,
    val lastClampOne: Long,
    val lastClampTwo: Long,
    val lastChild: Long,
    val lastGrounded: Long,
    val isClamp: Long
)

data class ClampDetail ( val id: Long,
                         val ts: Long,
                         val lat: Double,
                         val lon: Double,
                         val spd: Double,
                         val gps: Double,
                         val lastOnsite: Boolean,
                         val createdBy: String,
                         val updatedBy: String,
                         val createdAt: String,
                         val updatedAt: String,
                         val lastTouchTime: String,
                         val lastTouchDate: String,
                         val lastTouchDateTime: String,
                         val position: Long,
                         val msl: Double)
